<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


function mega_main_menu_block_info() {
    $blocks['megamenu'] = array(
        'info' => t('Mega Main Menu'),
        'status' => TRUE,
        'region' => 'main_menu',
        'visibility' => BLOCK_VISIBILITY_PHP,
    );
    return $blocks;
}

function mega_main_menu_block_view($delta = '') {

    $block = array();
	
    if ($delta == 'megamenu') {
    
		$menu_name = 'main-menu';
		
        $active_path = menu_tree_get_path($menu_name);
		
        $router_item = menu_get_item($active_path);
		
        $active_link = menu_link_get_preferred($active_path, $menu_name);

        $menus = menu_tree_all_data($menu_name);
		
        $block['content'] = '<nav id="a_nav" class="main-nav" role="navigation"><ul>';
        
        $mlids = db_query("SELECT mlid, p9, p8, p7, p6, p5, p4, p3, p2, p1 FROM {menu_links} WHERE link_path = :link AND menu_name = :name ", array(':link' => $router_item['tab_root_href'], ':name' => $menu_name ))->fetchAll();
        
        $mlids = (isset($mlids[0]) && !empty($mlids[0])) ? ((array)$mlids[0]) : array();      

        $content = "";
		
        mega_main_menu_generateMegaMenu($menus, $active_link, $router_item, $mlids, $content);

        $block['content'] .= $content;

        $block['content'] .= '</ul></nav> <!-- // menu -->';
    }

    return $block;
}


function mega_main_menu_getAtMegaMenu() { 
    
  $links = array();
  $query = db_select('node','n');
  $query->fields('n', array("nid", "created"));
  $query->fields('ml', array("mlid"));
  $query->innerJoin('field_data_field_at_mega_menu', 'at', '(n.nid = at.entity_id AND at.field_at_mega_menu_value = 1)');
  $query->innerJoin('menu_links', 'ml', 'n.nid = SUBSTRING(ml.link_path,6)');
  $query->condition('n.status', '1', '=');
  $query->orderBy('n.created', 'DESC');
  $result = $query->execute()->fetchAll();
  
  foreach ($result as $rs) {
      $links[$rs->created] = $rs->mlid;
  }
  return $links;
}



function mega_main_menu_generateMegaMenu($menus, $active_link, $router_item, $mlids, &$content) {

	$at_mega_menu = mega_main_menu_getAtMegaMenu();
	foreach ($menus as $menu){
		$atMegaMenuLinks = array();
		if ($menu['link']['hidden'] != 1) {
			$class = '';
			$active_menu = '';
			if ($menu['link']['href'] == $router_item['tab_root_href'] || (!empty($active_link['plid']) && $active_link['plid'] == $menu['link']['mlid']) || (in_array($menu['link']['mlid'], $mlids))) {
				$active_menu = 'active';
				$class = ' active';
			}
			$__link = $menu['link']['title'];
			$__options = array('attributes' => array('class' => array($active_menu),), 'html' => TRUE, 'external' => TRUE);
			$link = url($menu['link']['href']);
			
				
			$content .= '<li class="' . $class . '">'; // niveau 1
			$content .= l($__link, $link, $__options);
			if (!empty($menu['below'])) {
				$content .= '<div class="sub-nav"><div class="box-wrapper">';
				foreach ($menu['below'] as $subMenu1){                   
					
					$content .= '<div class="box box-1of5 box-xs-full">'; // niveau 2

					$activeMenuSub1 = '';
					if ($subMenu1['link']['href'] == $router_item['tab_root_href'] || (!empty($active_link['plid']) && $active_link['plid'] == $subMenu1['link']['mlid']) || (in_array($subMenu1['link']['mlid'], $mlids))) {
						$activeMenuSub1 = 'active';
					}
					$__options = array('attributes' => array('class' => array($activeMenuSub1),), 'html' => TRUE, 'external' => TRUE);
					$linkSubMenu1 = l($subMenu1['link']['title'], url($subMenu1['link']['href']), $__options);
					$content .= '<h2 class="subnav-title">' . $linkSubMenu1 . '</h2>';   
					if (!empty($subMenu1['below'])) {
						$content .= '<ul class="subnav-list">';
						foreach ($subMenu1['below'] as $key2 => $subMenu2){
							if ($key = array_search($subMenu2['link']['mlid'], $at_mega_menu))
							{ 
								$atMegaMenuLinks[$key] = $subMenu2;							
								unset($subMenu1['below'][$key2]);
								continue;
							}
							$activeMenuSub2 = '';
							if ($subMenu2['link']['href'] == $router_item['tab_root_href'] || (!empty($active_link['plid']) && $active_link['plid'] == $subMenu2['link']['mlid']) || (in_array($subMenu2['link']['mlid'], $mlids))) {
								$activeMenuSub2 = 'active';
							}
							$__options = array('attributes' => array('class' => array($activeMenuSub2),), 'html' => TRUE, 'external' => TRUE);
							$linkSubMenu2 = l($subMenu2['link']['title'], url($subMenu2['link']['href']), $__options);
							$content .= '<li>' . $linkSubMenu2 . '</li>'; // niveau 3
						}
						$content .= '</ul>';
					}
					
					$content .= '</div>';
					
				}
				
				$content .= '</div>';
				
				/// Ici a la une mega menu
				
				// Trier par date de publication
				rsort($atMegaMenuLinks);
				
				// Prendre uniquement les 3 derniers items
				$atMegaMenuLinks = array_slice($atMegaMenuLinks, 0, 3);
				
				if (!empty($atMegaMenuLinks)) {
					$content .= '<div class="box-wrapper box-gutter box-big-links">';
					foreach ($atMegaMenuLinks as $key2 => $atMegaMenu){
					
						$content .= '<div class="box box-1of3 box-xs-full">';
						$pathIcon = (isset($atMegaMenu['link']['options']['menu_icon']['path'])) ? $atMegaMenu['link']['options']['menu_icon']['path'] : '';
						
						$Icon = '';
						if(!empty($pathIcon)){
							$Icon = '<img src="' . file_create_url($pathIcon) . '" alt="">';
						}
						$classActiveIcon = '';
						if ($atMegaMenu['link']['href'] == $router_item['tab_root_href'] || (!empty($active_link['plid']) && $active_link['plid'] == $atMegaMenu['link']['mlid']) || (in_array($atMegaMenu['link']['mlid'], $mlids))) {
							$classActiveIcon = 'active_item';
						}
						$linkIcon = '<span class="nav-icon">' . $Icon . '</span><span class="link-text">' . $atMegaMenu['link']['title'] . '</span>';
						$__options = array('attributes' => array('class' => array($classActiveIcon),), 'html' => TRUE, 'external' => TRUE);
						$content .= l($linkIcon, url($atMegaMenu['link']['href']), $__options);
						
						$content .= '</div>';
					
					}				
					
					$content .= '</div>';
				}
				
				$content .= '</div>';
				
				/// Ici a la une mega menu

				$content .= '</li>';
				
			}

		}
	}        
}