<?php

/**
 * @file
 * Module portal_config
 * Configuration des destinataires des emails dans le formulaire de contact ...
 */

/**
 * Hook Permission Enter description here ...
 * @return mixed
 *   Description.
 */
function portal_config_permission() {
  return array(
    'access configuration portail' => array(
      'title' => t('Administer Portail Config'),
    ),
  );
}

/**
 * Création du menu portal_config.
 * @return mixed
 *   Description.
 */
function portal_config_menu() {
  $items['admin/portal_config'] = array(
    'title' => 'Config Portail',
    'title callback' => 'Config Portail',
    'page callback' => 'get_form_config_portal',
    'access arguments' => array('access configuration portail'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Génération du formulaire de configuration des destinataires.
 * @return mixed
 *   Description.
 */
function form_config_portal() {
  $form = array();

  /*
   * Configuration Site Qualité AFNOR CERTIFICATION ISO 3001
   */
  $form['uti_group_afaq'] = array(
    '#type' => 'fieldset',
    '#title' => t('Configuration Site Qualité AFNOR CERTIFICATION ISO 3001'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['uti_group_afaq']['uti_group_afaq_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Url Footer'),
    '#default_value' => variable_get('uti_group_afaq_url', ''),
  );

  return system_settings_form($form);
}

/**
 * Retourner le formulaire de configuration.
 * @return mixed
 *   Description.
 */
function get_form_config_portal() {
  return drupal_get_form('form_config_portal');
}
