<?php

/**
 * @file
 * drs_breadcrumb/drs_breadcrumb.module Customizing breadcrumb.
 * @author mhammami
 */

/**
 * Implements hook_menu_breadcrumb_alter().
 */
function drs_breadcrumb_menu_breadcrumb_alter(&$active_trail, $item) {

  if (isset($item['load_functions'][1]) && !empty($item['map'][1]) && $item['load_functions'][1] == 'node_load') {
    // The current page  is a node page.
    $node = $item['map'][1];

    switch ($node->type) {
      case 'actuality':
        $active_trail[1] = array(
          'title' => t('News list'),
          'href' => 'liste-actualités',
          'link_path' => '',
          'localized_options' => array(),
          'type' => 0,
        );
        $active_trail[2] = array(
          'title' => $node->title,
          'href' => "node/$node->nid",
          'link_path' => '',
          'localized_options' => array(),
          'type' => 0,
        );
        break;

      case 'minisite':
        // Home: content fond to witch mimisite is attached.

        $active_trail[0] = array(
          'title' => t('Home'),
          'href' => "node/$node->nid",
          'link_path' => '',
          'localized_options' => array(),
          'type' => 0,
        );
        unset($active_trail[1]);

        // Intermediate links: get menu minisite links.
        $mini_site_title = str_replace(' ', '-', $node->title);
        if ($menu_minisite = menu_tree_all_data("menu-site-{$mini_site_title}")) {

          $current_path = current_path();

          foreach ($menu_minisite as $menu_link) {
            if ($menu_link['link']['link_path'] == $current_path) {
              $active_trail[1] = array(
                'title' => $menu_link['link']['link_title'],
                'href' => $menu_link['link']['link_path'],
                'link_path' => '',
                'localized_options' => array(),
                'type' => 0,
              );
              break;
            }

            if ($menu_link['below']) {
              foreach ($menu_link['below'] as $menu_sub_link) {
                if ($menu_sub_link['link']['link_path'] == $current_path) {
                  $active_trail[1] = array(
                    'title' => $menu_link['link']['link_title'],
                    'href' => $menu_link['link']['link_path'],
                    'link_path' => '',
                    'localized_options' => array(),
                    'type' => 0,
                  );

                  $active_trail[2] = array(
                    'title' => $menu_sub_link['link']['link_title'],
                    'href' => $menu_sub_link['link']['link_path'],
                    'link_path' => '',
                    'localized_options' => array(),
                    'type' => 0,
                  );
                  break;
                }
              }
            }
          }
        }
        break;

      default:
    }
  }
}
