<?php

/**
 * @file
 * drs_global_functions/drs_global_functions.module Set up global functions.
 * @author mhammami
 */

/**
 * Get Web form Trouver Regime De Retraite Nid.
 *
 * @param string $title
 *   title.
 *
 * @return mixed
 *   boolean.
 */

function utigroup_global_functions_exist($e){
    if(isset($e) && !empty($e))
        return join(' ', $e);
    else
        return '';
}


function utigroup_global_functions_menu() {
    $items['donnees'] = array(
        'title' => 'Données financières',
        'page callback' => 'get_latest_news',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    
    return $items;
}

function get_latest_news() {
    return array();
}
